export const IP_URI = "https://api.ipify.org"
export const BASE_API_URI = "https://bubbles-api-a6hm.onrender.com"
export const BASE_API_URI_LOCAL = "http://localhost:8000"
export const BASE_APP_URI = "https://bubbles-inc.vercel.app"
export const BASE_APP_URI_LOCAL = "http://localhost:3000"
export const GITHUB_URI = "https://github.com/binaryshrey/Bubbles"
export const GITHUB_ISSUES_URI = "https://github.com/binaryshrey/Bubbles/issues"
export const LINKEDIN_URI = "https://in.linkedin.com/in/shreyanshsaurabh"
export const BETTERSTACK_URI = "https://bubbles.betteruptime.com/"

